#!/bin/sh

if [ -z $WAYLAND_DISPLAY ]; then
    >&2 echo "no idle daemon for xorg!"
else
    killall -q swayidle
    echo "waiting on old daemon to die"
    while pgrep -u $UID -x swayidle >/dev/null; do sleep 1; done

    echo "launching new daemon..."
    swayidle -w \
        timeout 600 'if pgrep swaylock; then systemctl suspend; fi' \
        before-sleep 'lock-screen'
fi
