#!/bin/sh

if [ $# -gt 0 ]; then
    mkdir "$1"
    cd "$1"
    echo "\documentclass[a4paper]{article}

\usepackage{amsmath} \usepackage{commath} \usepackage{siunitx}
\usepackage{enumitem} \usepackage{graphicx} \usepackage{titlesec}
\usepackage{xifthen} \usepackage{amssymb} \usepackage{amsthm}

\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\F}{\mathbb{F}}
\newcommand{\M}{\mathcal{M}}
\newcommand{\defn}{\textbf{defn:} }
\newcommand{\prop}[1][]{\textbf{proposition}\ifthenelse{\isempty{#1}}{}{\textbf{
(}\textbf{#1}\textbf{)}}\textbf{:} } \newcommand{\claim}{\textbf{claim:} }
\newcommand{\prf}{\textbf{proof:} } \newcommand{\eg}{\textbf{example:} }
\newcommand{\rmk}{\textbf{remark:} }

\addtolength{\jot}{1em} \titlespacing*{\section} {0pt}{5.5ex plus 1ex minus
.2ex}{4.3ex plus .2ex} \titlespacing*{\subsection} {0pt}{5.5ex plus 1ex minus
.2ex}{4.3ex plus .2ex}

\title{$1} \author{Luminiscental}

\setlength{\parindent}{0cm}

\begin{document}

\maketitle

\end{document}" > "$1.tex"

    nvim "$1.tex"

else
    echo "Please specify a name for the project"
fi

