#!/usr/bin/env python


import subprocess
import re
import sys


BLACKLIST = ["acpitz", "iwlwifi", "ath10k", "ucsi", "BAT0", "nct6798-isa-0290"]


def get_paragraphs(lines):
    def take_paragraph(lines):
        assert lines
        header = lines[0]
        end = 1
        while end < len(lines) and lines[end]:
            end += 1
        return header, lines[1:end], lines[end + 1 :]

    paragraphs = {}
    while lines:
        header, body, lines = take_paragraph(lines)
        paragraphs[header] = body
    return paragraphs


def ralign_after(pat, string, pad):
    before, after = string.split(pat, 1)
    before = before.strip()
    after = after.strip()
    return before + pat + " " * (pad - len(before) - len(after)) + after


def display_body(lines, width):
    return ["  " + ralign_after(":", line, width) for line in lines]


def main():
    width = int(sys.argv[1])
    raw = subprocess.check_output("sensors").decode("utf-8")
    parens = re.compile(r"\(.*?\)")
    paragraphs = get_paragraphs(
        [
            re.sub(parens, "", line).strip()
            for line in map(str.strip, raw.splitlines())
            if line.split(":", 1)[0] not in ("Adapter", "Package id 0")
            and not parens.match(line)
        ]
    )
    print(
        "\n\n".join(
            sorted(
                "\n".join([header] + display_body(body, width))
                for header, body in paragraphs.items()
                if not any(header.startswith(w) for w in BLACKLIST)
            )
        )
    )


if __name__ == "__main__":
    main()


# vim: set syntax=python:
