#!/bin/sh

if [ -z $WAYLAND_DISPLAY ]; then
    killall -q conky
    while pgrep -u $UID -x conky >/dev/null; do sleep 1; done

    #ARGS="--own_window_type='override'"
    conky -dq -c ~/.local/share/conky/system-i3.conf
    conky -dq -c ~/.local/share/conky/todo-i3.conf
else
    until pgrep waybar >/dev/null; do sleep 1; done

    killall -q conky
    while pgrep -u $UID -x conky >/dev/null; do sleep 1; done

    conky -dq -c ~/.local/share/conky/system-sway.conf
    conky -dq -c ~/.local/share/conky/todo-sway.conf

    # nwg-wrapper \
    #     -a start \
    #     -p left  \
    #     -ml 30 -mt 30 \
    #     -c ~/.local/share/system-panels/style.css \
    #     -s ~/.local/share/system-panels/system.sh -r 2000 &
    # 
    # nwg-wrapper \
    #     -a start \
    #     -p right \
    #     -mr 30 -mt 30 \
    #     -c ~/.local/share/system-panels/style.css \
    #     -s ~/.local/share/system-panels/todo.sh -r 2000 &
fi
