#!/bin/sh

killall -q conky
while pgrep -u $UID -x conky >/dev/null; do sleep 1; done

if [ -z $WAYLAND_DISPLAY ]; then
    #ARGS="--own_window_type='override'"
    conky -dq -c ~/.local/share/conky/system-i3.conf
    conky -dq -c ~/.local/share/conky/todo-i3.conf
else
    #ARGS="--out_to_x=false --out_to_wayland=true"
    conky -dq -c ~/.local/share/conky/system-sway.conf
    conky -dq -c ~/.local/share/conky/todo-sway.conf
fi


# # conservative sleeping to make sure things are fine on startup
# sleep 2
# 
# # kill old instances
# killall -s 2 -q nwg-wrapper
# while pgrep -u $UID -x nwg-wrapper >/dev/null; do sleep 1; done
# 
# # launch new instances
# nwg-wrapper \
#     -a start \
#     -p left  \
#     -ml 30 -mt 30 \
#     -c ~/.local/share/system-panels/style.css \
#     -s ~/.local/share/system-panels/system.sh -r 2000 &
# 
# nwg-wrapper \
#     -a start \
#     -p right \
#     -mr 30 -mt 30 \
#     -c ~/.local/share/system-panels/style.css \
#     -s ~/.local/share/system-panels/todo.sh -r 2000 &
# 
# echo "Panels launched..."
