#!/bin/sh

if [ -z "$WAYLAND_DISPLAY" ]; then
    betterlockscreen -l dimblur &
else
    swaylock -f \
        --image ~/Documents/wallpapers/samantha-gades-blur.jpg \
        --indicator-idle-visible \
        --ring-color 685742 \
        --key-hl-color 9d6a47
fi
